import { RouterProvider, createRouter } from '@tanstack/react-router';
import { routeTree } from './routes/routeTree.gen';

// Register the route tree (auto-generated by TanStack Router)
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

export const router = createRouter({
  routeTree,
  basepath: '/',
  defaultPendingMs: 0,
  defaultPendingMinMs: 150,
});

// Export the RouterProvider for use in App
export function Router() {
  return <RouterProvider router={router} />;
}
