/**
 * Pure formatters for the popup's "Export .env" feature.
 *
 * The threat-model contract: this module runs **entirely in the
 * browser** with the already-decrypted `VaultPlain` and produces
 * strings the user can download. The sync server never sees any
 * of this, never decrypts anything, and gains no new powers.
 *
 * Why a separate module: keeping the formatting + sanitisation
 * logic here lets us unit-test the edge cases (special chars,
 * collisions, empty vault) without rendering a React component.
 */

import type { VaultPlain } from './vault';

export interface EnvExportOptions {
  /** If set, only include keys whose name matches one of these.
   *  Names match against the original (lowercase) vault key, NOT
   *  the converted ENV_NAME. */
  selectedNames?: string[];
  /** If true, append `# (no value)` for keys whose value is empty.
   *  Default: false (skip empty-valued keys entirely). */
  keepEmpty?: boolean;
  /** Override the timestamp in the file header. Test-only. */
  now?: Date;
}

const DEFAULT_HEADER_LINES = [
  '# Generated by KeyShield. End-to-end encrypted vault export.',
  '#',
  '# DO NOT COMMIT THIS FILE TO GIT.',
  '# Add `.env` to your .gitignore. The popup downloads a',
  '# `.env.example` template alongside this file — commit that',
  '# instead so collaborators know which keys are needed.',
];

/**
 * Convert a vault key name (e.g. `openai-prod`) into a POSIX-style
 * environment variable name (e.g. `OPENAI_PROD`). Hyphens, dots, and
 * spaces become underscores; uppercase the lot; strip anything that
 * isn't `[A-Z0-9_]`. Leading digits are prefixed with an underscore
 * because POSIX env names can't start with a digit.
 */
export function toEnvName(name: string): string {
  let out = name
    .replace(/[\s./\\-]+/g, '_')
    .toUpperCase()
    .replace(/[^A-Z0-9_]/g, '');
  if (out.length === 0) return '';
  if (/^[0-9]/.test(out)) out = '_' + out;
  return out;
}

/**
 * Quote a value the way `dotenv`/`docker --env-file` expect.
 *
 *   - empty strings → empty value (no quotes; just `KEY=`).
 *   - simple printable ASCII without whitespace, `#`, `'`, `"`, `\`
 *     or newlines → unquoted.
 *   - everything else → double-quoted with backslash-escaped `\`,
 *     `"`, `$`, and `\n`/`\r`. Newlines collapse to `\n` literals.
 */
export function quoteEnvValue(value: string): string {
  if (value.length === 0) return '';
  const SAFE = /^[A-Za-z0-9_\-+.,/:@!=?]+$/;
  if (SAFE.test(value)) return value;
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/\r?\n/g, '\\n')
    .replace(/\r/g, '\\r');
  return `"${escaped}"`;
}

/**
 * Format a vault as `.env` text content. Always deterministic:
 * keys are sorted, header is fixed-format, no trailing whitespace.
 */
export function formatVaultAsEnv(
  vault: VaultPlain,
  opts: EnvExportOptions = {},
): string {
  const ts = (opts.now ?? new Date()).toISOString();
  const filterSet = opts.selectedNames
    ? new Set(opts.selectedNames)
    : null;

  const seenEnvNames = new Map<string, string>();
  const rows: Array<{ envName: string; value: string; sourceName: string }> = [];

  for (const sourceName of Object.keys(vault.apiKeys).sort((a, b) => a.localeCompare(b))) {
    if (filterSet && !filterSet.has(sourceName)) continue;
    const rec = vault.apiKeys[sourceName];
    const value = rec?.value ?? '';
    if (value === '' && !opts.keepEmpty) continue;

    let envName = toEnvName(sourceName);
    if (envName === '') {
      // Vault key contained no env-name-safe characters at all.
      // Skip — there's no representation we can give it.
      continue;
    }

    // De-collide: `openai-prod` and `OPENAI_PROD` would both map
    // to `OPENAI_PROD`. Append `_2`, `_3`, ... to the second-to-N.
    if (seenEnvNames.has(envName)) {
      let n = 2;
      while (seenEnvNames.has(`${envName}_${n}`)) n++;
      envName = `${envName}_${n}`;
    }
    seenEnvNames.set(envName, sourceName);
    rows.push({ envName, value, sourceName });
  }

  const headerLines = [
    ...DEFAULT_HEADER_LINES,
    `# Generated at ${ts}`,
    `# Keys: ${rows.length}`,
    '',
  ];

  const bodyLines = rows.map(
    ({ envName, value }) => `${envName}=${quoteEnvValue(value)}`,
  );

  return [...headerLines, ...bodyLines, ''].join('\n');
}

/**
 * Format a `.env.example` template — same key names as the export,
 * no values. Safe to commit.
 */
export function formatVaultAsEnvExample(
  vault: VaultPlain,
  opts: EnvExportOptions = {},
): string {
  const ts = (opts.now ?? new Date()).toISOString();
  const filterSet = opts.selectedNames
    ? new Set(opts.selectedNames)
    : null;

  const seenEnvNames = new Set<string>();
  const rows: string[] = [];

  for (const sourceName of Object.keys(vault.apiKeys).sort((a, b) => a.localeCompare(b))) {
    if (filterSet && !filterSet.has(sourceName)) continue;
    let envName = toEnvName(sourceName);
    if (envName === '') continue;
    if (seenEnvNames.has(envName)) {
      let n = 2;
      while (seenEnvNames.has(`${envName}_${n}`)) n++;
      envName = `${envName}_${n}`;
    }
    seenEnvNames.add(envName);
    rows.push(envName);
  }

  return [
    '# .env.example — committable template, generated by KeyShield.',
    '# Copy this to .env and fill in real values from your vault.',
    `# Generated at ${ts}`,
    '',
    ...rows.map((n) => `${n}=`),
    '',
  ].join('\n');
}

/**
 * Browser-side: trigger a download of `content` as `filename`.
 * Uses a Blob + ObjectURL so the download survives without a
 * server round-trip.
 *
 * Not used by the test runner (it has no `document`); call from
 * the popup component directly.
 */
export function triggerDownload(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  // Use a microtask to give the browser a tick to actually start
  // the download before we revoke the URL.
  queueMicrotask(() => {
    a.remove();
    URL.revokeObjectURL(url);
  });
}
