//! Token-usage extraction + cost computation.
//!
//! Verbatim port of `v2-mvp/src/usage.py:23-43` (the cost tables) and
//! `usage.py:99-129` (`extract_token_usage` + `_flat_cost`). The Rust side
//! is now the source-of-truth for the numbers we send to Python via the
//! `_internal/log` bridge — see ADR-001 #7 and spec 07-bridge.md.
//!
//! Drift between Python and Rust here = under-/over-charging users.
//! Tests in `tests/usage.rs` lock parity against fixtures generated by
//! re-running Python.

use std::collections::HashMap;
use std::sync::OnceLock;

/// Per-1k-token cost (USD) per upstream: `(input_per_1k, output_per_1k)`.
///
/// Mirrors `COST_PER_1K` in `usage.py:23-37`.
fn cost_per_1k() -> &'static HashMap<&'static str, (f64, f64)> {
    static TABLE: OnceLock<HashMap<&'static str, (f64, f64)>> = OnceLock::new();
    TABLE.get_or_init(|| {
        let mut m = HashMap::with_capacity(10);
        m.insert("openai", (0.003, 0.012));
        m.insert("anthropic", (0.003, 0.015));
        m.insert("groq", (0.0006, 0.0008));
        m.insert("mistral", (0.0002, 0.0006));
        m.insert("cohere", (0.001, 0.002));
        // Non-AI: no per-token cost; tiny flat rate per call when platform key is used.
        m.insert("helius", (0.0, 0.0));
        m.insert("0x", (0.0, 0.0));
        m.insert("titan", (0.0, 0.0));
        m.insert("pyth", (0.0, 0.0));
        m.insert("alchemy", (0.0, 0.0));
        m
    })
}

/// Flat per-call cost for non-AI upstreams (USD) when the platform key is used.
///
/// Mirrors `FLAT_COST_PER_CALL` in `usage.py:40-43`.
fn flat_cost_per_call() -> &'static HashMap<&'static str, f64> {
    static TABLE: OnceLock<HashMap<&'static str, f64>> = OnceLock::new();
    TABLE.get_or_init(|| {
        let mut m = HashMap::with_capacity(2);
        m.insert("helius", 0.00001);
        m.insert("alchemy", 0.00001);
        m
    })
}

/// New-user free credit, mirrors `usage.py:46`.
pub const FREE_CREDIT_USD: f64 = 0.10;

fn flat_cost(upstream: &str) -> f64 {
    flat_cost_per_call().get(upstream).copied().unwrap_or(0.0)
}

/// Parse a proxy response body and return `(tokens_in, tokens_out, cost_usd)`.
///
/// Mirrors `usage.extract_token_usage(upstream, content)` in
/// `usage.py:99-125`:
///
/// - Empty / non-JSON / non-UTF-8 body → `(0, 0, _flat_cost(upstream))`
/// - OpenAI-shaped: `usage.{prompt_tokens, completion_tokens}`
/// - Anthropic-shaped: `usage.{input_tokens, output_tokens}`
/// - Cost: `tok_in/1000*in_rate + tok_out/1000*out_rate`. If 0, fall back
///   to the flat per-call cost.
pub fn extract_token_usage(upstream: &str, content: &[u8]) -> (u64, u64, f64) {
    if content.is_empty() {
        return (0, 0, flat_cost(upstream));
    }

    // Python's `json.loads(bytes)` rejects invalid UTF-8 with a
    // UnicodeDecodeError (caught upstream → flat cost). serde_json accepts
    // any valid JSON regardless of leading BOM, but for an invalid-utf8
    // body it returns a parse error — same observable result.
    let data: serde_json::Value = match serde_json::from_slice(content) {
        Ok(v) => v,
        Err(_) => return (0, 0, flat_cost(upstream)),
    };

    let (mut tok_in, mut tok_out) = (0u64, 0u64);
    if let Some(obj) = data.as_object() {
        if let Some(usage_val) = obj.get("usage").and_then(|v| v.as_object()) {
            // OpenAI-compat fields take precedence; Anthropic-only fields are
            // the fallback. Mirrors the `or` chain in usage.py:116-117.
            tok_in = usage_val
                .get("prompt_tokens")
                .and_then(json_u64)
                .or_else(|| usage_val.get("input_tokens").and_then(json_u64))
                .unwrap_or(0);
            tok_out = usage_val
                .get("completion_tokens")
                .and_then(json_u64)
                .or_else(|| usage_val.get("output_tokens").and_then(json_u64))
                .unwrap_or(0);
        }
    }

    let (in_rate, out_rate) = cost_per_1k().get(upstream).copied().unwrap_or((0.0, 0.0));
    let mut cost = tok_in as f64 / 1000.0 * in_rate + tok_out as f64 / 1000.0 * out_rate;

    // `usage.py:122` — `if cost == 0.0: cost = _flat_cost(upstream)`. Note
    // this fires both for non-AI upstreams (no rate) AND for AI upstreams
    // whose response had no `usage` field. We mirror that exactly.
    if cost == 0.0 {
        cost = flat_cost(upstream);
    }

    (tok_in, tok_out, cost)
}

/// Coerce a JSON value (`Number` only) into `u64` the same way Python's
/// `int(...) or 0` falls out for clean integer responses. Matches the
/// `(usage.get("prompt_tokens") or 0)` short-circuit in `usage.py:116-117`:
/// `None`, `0`, and missing all collapse to `0`.
fn json_u64(v: &serde_json::Value) -> Option<u64> {
    // serde_json's u64 accessor handles JSON integers; floats round.
    v.as_u64().or_else(|| v.as_f64().map(|f| f as u64))
}
