// This file is auto-generated by TanStack Router's codegen.
// It declares all routes and the route tree.

import { createRootRoute, createRoute } from '@tanstack/react-router';
import App from '../App';

const rootRoute = createRootRoute();

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: App,
});

export const routeTree = rootRoute.addChildren([indexRoute]);
