"""Type stubs for KeyShield v2-MVP public API."""

# ─── Vault ──────────────────────────────────────────────────────────────

def store(user_id: str, upstream: str, api_key: str, password: str) -> None: ...
def delete(user_id: str, upstream: str) -> None: ...
def list_keys(user_id: str) -> list[str]: ...
def load(user_id: str, upstream: str, password: str) -> str: ...
def migrate_all_to_argon2(user_id: str) -> int: ...

VAULT_DIR: str
SALT_LEN: int
NONCE_LEN: int
KDF_ITERS: int

# ─── Session ─────────────────────────────────────────────────────────────

def create_token(user_id: str, password: str, ttl: int = ...) -> str: ...
def get(token: str) -> dict | None: ...
def verify_token(token: str) -> tuple[bool, str | None]: ...
def delete(token: str) -> None: ...
def delete_all_for_user(user_id: str) -> int: ...
def mark_deleted(user_id: str) -> None: ...
def is_deleted(user_id: str) -> bool: ...
def extend_token(token: str, extra_secs: int = ...) -> bool: ...

SESSION_TTL: int

# ─── Agent ──────────────────────────────────────────────────────────────

def register(owner_wallet: str, pubkey_b58: str, name: str = ..., scopes: str = ...) -> int: ...
def lookup_owner(pubkey_b58: str) -> dict | None: ...
def revoke_agent(owner_wallet: str, agent_id: int, reason: str = ...) -> bool: ...
def list_agents(owner_wallet: str) -> list[dict]: ...
def revoke(owner_wallet: str, agent_id: int) -> bool: ...
def touch(pubkey_b58: str) -> None: ...
def purge_user(user_id: str) -> dict: ...

# ─── Proxy ──────────────────────────────────────────────────────────────

async def call_helius(method: str, params: list, api_key: str, rpc_id: int = ...) -> tuple[dict, str]: ...
async def call_rest(provider_name: str, method: str, path: str, body: bytes, api_key: str, extra_headers: dict | None = ...) -> tuple[bytes, int, str]: ...
async def batch_helius(requests: list[dict], api_key: str) -> list[dict]: ...
async def batch_rest(provider_name: str, requests: list[dict], api_key: str) -> list[dict]: ...
def cache_stats() -> dict: ...

# ─── Billing ─────────────────────────────────────────────────────────────

def log_call(user_id: str, upstream: str, key_type: str, ...) -> None: ...
def get_stats(user_id: str) -> dict: ...
def get_history(user_id: str, limit: int = ...) -> list[dict]: ...
def get_balance(user_id: str) -> float: ...
def topup(user_id: str, amount_usd: float) -> float: ...

# ─── Sharing ─────────────────────────────────────────────────────────────

def grant(owner_id: str, recipient_id: str, key_name: str, ...) -> int: ...
def revoke(owner_id: str, share_id: int) -> bool: ...
def list_outgoing(owner_id: str) -> list[dict]: ...
def list_incoming(recipient_id: str) -> list[dict]: ...
def purge_user(user_id: str) -> int: ...

# ─── MPP ─────────────────────────────────────────────────────────────────

class MppConfig:
    secret_key: bytes
    settler_pubkey: str
    platform_usdc_ata: str
    keyshield_program_id: str
    usdc_mint: str
    vault_pda: str | None
    rpc_url: str

def load_mpp_config() -> MppConfig | None: ...
def build_mpp_settle_ix_data(amount_micro_usdc: int) -> bytes: ...
def build_mpp_settle_ix(config: MppConfig, stream_pda: str, stream_ata: str, amount: int) -> dict: ...
async def submit_mpp_settle(config: MppConfig, ix: dict) -> int: ...

# ─── Agent Wallet ───────────────────────────────────────────────────────

def build_create_ephemeral_signer_ix_data(allowed_actions: int, expiry_seconds: int) -> bytes: ...
def build_create_ephemeral_signer_ix(config: MppConfig, ...) -> dict: ...
def derive_ephemeral_signer_pda(agent_pubkey: str, owner_pubkey: str, program_id: str) -> tuple[str, int]: ...

# ─── Helius Skill ───────────────────────────────────────────────────────

async def portfolio(wallet: str, api_key: str) -> dict: ...
async def transactions(wallet: str, api_key: str, limit: int = ...) -> list[dict]: ...
async def nfts(wallet: str, api_key: str, limit: int = ..., page: int = ...) -> dict: ...
async def search_nfts(query: str, api_key: str, limit: int = ...) -> list[dict]: ...
async def token_info(mint: str, api_key: str) -> dict: ...
async def analyze_tx(signature: str, api_key: str) -> dict: ...
async def watch_wallet(wallet: str, webhook_url: str, api_key: str, event_types: list[str] | None = ...) -> dict: ...
async def list_webhooks(api_key: str) -> list[dict]: ...
async def delete_webhook(webhook_id: str, api_key: str) -> dict: ...
async def run_tool(name: str, inputs: dict, api_key: str) -> object: ...
