import { describe, it, expect } from 'vitest';
import { parseEnvFile, lookupKey } from '../src/lib/env-file.js';

describe('parseEnvFile — basics', () => {
  it('parses a simple KEY=value file', () => {
    const r = parseEnvFile('OPENAI=sk-1\nSTRIPE=sk_live_2\n');
    expect(r.values.get('OPENAI')).toBe('sk-1');
    expect(r.values.get('STRIPE')).toBe('sk_live_2');
    expect(r.warnings).toHaveLength(0);
  });

  it('skips blank lines and #-comment lines', () => {
    const r = parseEnvFile(
      '# top comment\n\nOPENAI=sk-1\n\n   # indented comment\nSTRIPE=sk-2\n',
    );
    expect(r.values.size).toBe(2);
    expect(r.warnings).toHaveLength(0);
  });

  it('preserves insertion order', () => {
    const r = parseEnvFile('Z=z\nA=a\nM=m\n');
    expect([...r.values.keys()]).toEqual(['Z', 'A', 'M']);
  });

  it('last duplicate wins', () => {
    const r = parseEnvFile('K=first\nK=second\n');
    expect(r.values.get('K')).toBe('second');
  });
});

describe('parseEnvFile — quoting', () => {
  it('strips surrounding double quotes', () => {
    expect(parseEnvFile('K="hello world"\n').values.get('K')).toBe(
      'hello world',
    );
  });

  it('handles escapes inside quotes', () => {
    expect(parseEnvFile('K="a\\"b"\n').values.get('K')).toBe('a"b');
    expect(parseEnvFile('K="a\\\\b"\n').values.get('K')).toBe('a\\b');
    expect(parseEnvFile('K="line1\\nline2"\n').values.get('K')).toBe(
      'line1\nline2',
    );
    expect(parseEnvFile('K="cost: \\$5"\n').values.get('K')).toBe('cost: $5');
  });

  it('warns on unterminated quoted values', () => {
    const r = parseEnvFile('K="never closed\n');
    expect(r.values.has('K')).toBe(false);
    expect(r.warnings).toHaveLength(1);
    expect(r.warnings[0].reason).toMatch(/unterminated/);
  });

  it('treats # without leading space as part of bare values', () => {
    // Common in URLs: postgres://u:p@host/db?sslmode=require#fragment
    expect(
      parseEnvFile('DB=postgres://u:p@host/db#frag\n').values.get('DB'),
    ).toBe('postgres://u:p@host/db#frag');
  });

  it('strips trailing comments after a space-#', () => {
    expect(parseEnvFile('K=value # commenty\n').values.get('K')).toBe('value');
  });

  it('warns on garbage lines', () => {
    const r = parseEnvFile('this is not a key=value pair\n');
    expect(r.warnings).toHaveLength(1);
    expect(r.warnings[0].reason).toMatch(/not a KEY=value/);
  });

  it('round-trips the popup format with header comments + quoted special chars', () => {
    const popupOutput = [
      '# Generated by KeyShield. End-to-end encrypted vault export.',
      '#',
      '# DO NOT COMMIT THIS FILE TO GIT.',
      '# Generated at 2026-04-28T12:00:00.000Z',
      '# Keys: 3',
      '',
      'ANTHROPIC=sk-ant-zzz',
      'NOTE="has spaces and #hash"',
      'OPENAI_PROD=sk-abc',
      '',
    ].join('\n');
    const r = parseEnvFile(popupOutput);
    expect(r.warnings).toHaveLength(0);
    expect(r.values.size).toBe(3);
    expect(r.values.get('ANTHROPIC')).toBe('sk-ant-zzz');
    expect(r.values.get('NOTE')).toBe('has spaces and #hash');
    expect(r.values.get('OPENAI_PROD')).toBe('sk-abc');
  });
});

describe('lookupKey', () => {
  function envWith(rows: Record<string, string>) {
    const values = new Map(Object.entries(rows));
    return { values, warnings: [] };
  }

  it('finds an exact match', () => {
    expect(lookupKey(envWith({ OPENAI: 'x' }), 'OPENAI')).toBe('x');
  });

  it('upcases and normalises hyphens for the lookup', () => {
    expect(lookupKey(envWith({ OPENAI_PROD: 'x' }), 'openai-prod')).toBe('x');
    expect(lookupKey(envWith({ OPENAI_PROD: 'x' }), 'openai.prod')).toBe('x');
  });

  it('falls back to a case-insensitive scan', () => {
    expect(lookupKey(envWith({ openai: 'x' }), 'OPENAI')).toBe('x');
  });

  it('returns undefined when nothing matches', () => {
    expect(lookupKey(envWith({ OPENAI: 'x' }), 'stripe')).toBeUndefined();
  });
});
